### ISSUE TITLE
about convert bert

### ISSUE THREAD

**Issue by JingnanXu97** [muziyongshixin/adv_cross_modal_hashing#3]
hello maybe my question is a little stupid, but it does huant for a few days... i try ro follow the website which you give but i cannot find bert_config.json..

**Comment by muziyongshixin** [comment]
> hello maybe my question is a little stupid, but it does huant for a few days... i try ro follow the website which you give but i cannot find bert_config.json..

the `t_cfg.json` file is the bert_config file
